# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(to='home.Category'),
        ),
    ]
