# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_movie_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='path',
            field=models.FileField(default=django.utils.timezone.now, upload_to='movies'),
            preserve_default=False,
        ),
    ]
