# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_movie_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='path',
            new_name='video',
        ),
    ]
